# Generated by Django 4.2.25 on 2025-10-04 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color', models.CharField(default='#ff6b6b', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(default='marker', help_text='Icon name for markers', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MapConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('center_latitude', models.DecimalField(decimal_places=6, default=21.0285, max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, default=105.8542, max_digits=9)),
                ('zoom_level', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('max_zoom', models.IntegerField(default=18)),
                ('min_zoom', models.IntegerField(default=1)),
                ('tile_layer', models.URLField(default='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', help_text='Tile layer URL for map background')),
                ('attribution', models.CharField(default='© OpenStreetMap contributors', max_length=200)),
                ('show_scale', models.BooleanField(default=True)),
                ('show_zoom_control', models.BooleanField(default=True)),
                ('show_layer_control', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='maps.category')),
            ],
            options={
                'verbose_name': 'Map Configuration',
                'verbose_name_plural': 'Map Configurations',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate (-90 to 90)', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate (-180 to 180)', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Vietnam', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True, help_text='Operating hours')),
                ('image', models.URLField(blank=True, help_text='Image URL')),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show as featured location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='maps.category')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='maps_locati_categor_c12631_idx'), models.Index(fields=['latitude', 'longitude'], name='maps_locati_latitud_82e01f_idx')],
            },
        ),
    ]
