# Generated by Django 4.2.25 on 2025-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_hierarchical_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hierarchicalcategory',
            name='unique_category_per_domain',
        ),
        migrations.RenameIndex(
            model_name='hierarchicalcategory',
            new_name='maps_hierar_domain__782381_idx',
            old_name='maps_hierarchicalcategory_domain_active_idx',
        ),
        migrations.RenameIndex(
            model_name='hierarchicalcategory',
            new_name='maps_hierar_externa_9d94c7_idx',
            old_name='maps_hierarchicalcategory_external_id_idx',
        ),
        migrations.RenameIndex(
            model_name='hierarchicallocation',
            new_name='maps_hierar_latitud_b3eb02_idx',
            old_name='maps_hierarchicallocation_lat_lng_idx',
        ),
        migrations.RenameIndex(
            model_name='hierarchicallocation',
            new_name='maps_hierar_city_c899e0_idx',
            old_name='maps_hierarchicallocation_city_active_idx',
        ),
        migrations.RenameIndex(
            model_name='hierarchicallocation',
            new_name='maps_hierar_locatio_772321_idx',
            old_name='maps_hierarchicallocation_location_id_idx',
        ),
        migrations.AlterField(
            model_name='domain',
            name='icon',
            field=models.CharField(default='Domain', help_text='Icon or label for domain', max_length=50),
        ),
        migrations.AlterField(
            model_name='hierarchicalcategory',
            name='icon',
            field=models.CharField(default='Category', help_text='Icon or label for category markers', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='hierarchicalcategory',
            unique_together={('domain', 'category_id')},
        ),
    ]
